<?php
/**
 * Class Mls_Config
 *
 * Communication between front-end and the back-end
 *
 * @class Mls_Config
 * @package Mls_Config
 * @version 1.0.0
 * @since 1.0.0
 * @author M Lab Studio
 */
if ( ! class_exists( 'Mls_Config' ) ) {
	class Mls_Config {
		/**
		 * All cities in Serbia
		 *
		 * @var string[]
		 */
		public $mls_cities = array(
			'Beograd',
			'Novi Sad',
			'Niš',
			'Kragujevac',
			'Ada',
			'Aleksandrovac',
			'Aleksinac',
			'Alibunar',
			'Apatin',
			'Aranđelovac',
			'Arilje',
			'Babušnica',
			'Bač',
			'Bačka',
			'Palanka',
			'Bačka Topola',
			'Bački Petrovac',
			'Bajina',
			'Bašta',
			'Batočina',
			'Bečej',
			'Bela Crkva',
			'Bela Palanka',
			'Beočin',
			'Blace',
			'Bogatić',
			'Bojnik',
			'Boljevac',
			'Bor',
			'Bosilegrad',
			'Brus',
			'Bujanovac',
			'Crna Trava',
			'Čačak',
			'Čajetina',
			'Ćićevac',
			'Čoka',
			'Ćuprija',
			'Dečani',
			'Despotovac',
			'Dimitrovgrad',
			'Doljevac',
			'Dragaš',
			'Đakovica',
			'Gadžin Han',
			'Glogovac',
			'Gnjilane',
			'Golubac',
			'Gornji',
			'Milanovac',
			'Inđija',
			'Irig',
			'Istok',
			'Ivanjica',
			'Jagodina',
			'Kačanik',
			'Kanjiža',
			'Kikinda',
			'Kladovo',
			'Klina',
			'Knić',
			'Knjaževac',
			'Koceljeva',
			'Kopaonik',
			'Kosjerić',
			'Kosovo Polje',
			'Kosovska Kamenica',
			'Kosovska Mitrovica',
			'Kovačica',
			'Kovin',
			'Kraljevo',
			'Krupanj',
			'Kruševac',
			'Kučevo',
			'Kula',
			'Kuršumlija',
			'Lajkovac',
			'Lapovo',
			'Lebane',
			'Leposavić',
			'Leskovac',
			'Lipljan',
			'Loznica',
			'Lučani',
			'Ljig',
			'Ljubovija',
			'Majdanpek',
			'Mali Iđoš',
			'Mali Zvornik',
			'Mališevo',
			'Malo Crniće',
			'Medveđa',
			'Merošina',
			'Mionica',
			'Negotin',
			'Nova Crnja',
			'Nova Varoš',
			'Novi Bečej',
			'Novi Kneževac',
			'Novi Pazar',
			'Novo Brdo',
			'Obilić',
			'Odžaci',
			'Opovo',
			'Orahovac',
			'Osečina',
			'Pančevo',
			'Paraćin',
			'Peć',
			'Pećinci',
			'Petrovacna Mlavi',
			'Pirot',
			'Plandište',
			'Podujevo',
			'Požarevac',
			'Požega',
			'Preševo',
			'Priboj',
			'Prijepolje',
			'Priština',
			'Prizren',
			'Prokuplje',
			'Rača',
			'Raška',
			'Ražanj',
			'Rekovac',
			'Ruma',
			'Sečanj',
			'Senta',
			'Sjenica',
			'Smederevo',
			'Smederevska Palanka',
			'Sokobanja',
			'Sombor',
			'Srbica',
			'Srbobran',
			'Sremska Mitrovica',
			'Sremski Karlovci',
			'Stara Pazova',
			'Subotica',
			'Surdulica',
			'Suva',
			'Reka',
			'Svilajnac',
			'Svrljig',
			'Šabac',
			'Šid',
			'Štimlje',
			'Štrpce',
			'Tara',
			'Temerin',
			'Titel',
			'Topola',
			'Trgovište',
			'Trstenik',
			'Tutin',
			'Ub',
			'Uroševac',
			'Užice',
			'Valjevo',
			'Varvarin',
			'Velika Plana',
			'Veliko Gradište',
			'Vitina',
			'Vladičin Han',
			'Vladimirci',
			'Vlasotince',
			'Vranje',
			'VranjskaBanja',
			'Vrbas',
			'Vrnjačka Banja',
			'Vršac',
			'Vučitrn',
			'Zaječar',
			'Zlatibor',
			'Zrenjanin',
			'Zubin Potok',
			'Zvečan',
			'Žabalj',
			'Žabari',
			'Žagubica',
			'Žitište',
			'Žitorađa'
		);

		public $mls_car_types = array(
			'AC',
			'Acura',
			'Alfa Romeo',
			'Alpina',
			'Aro',
			'Asia Motors',
			'Aston Martin',
			'Audi',
			'Autobianchi',
			'Bentley',
			'BMW',
			'Brilliance',
			'Bugatti',
			'Cadillac',
			'Chery',
			'Chevrolet',
			'Chrysler',
			'Citroen',
			'Comarth',
			'Cupra',
			'Dacia',
			'Daewoo',
			'Daihatsu',
			'Dodge',
			'DR',
			'Ferrari',
			'Fiat',
			'Ford',
			'GAZ',
			'GMC',
			'Great Wall',
			'GWM',
			'Honda',
			'Hummer',
			'Hyundai',
			'Infiniti',
			'Innocenti',
			'Isuzu',
			'Jaguar',
			'Jeep',
			'Katay Gonow',
			'Kia',
			'KTM',
			'Lada',
			'Lamborghini',
			'Lancia',
			'Land Rover',
			'Lexus',
			'Ligier',
			'Lincon',
			'Linzda',
			'Lotus',
			'Mahindra',
			'Maserati',
			'Matra',
			'Maybach',
			'Mazda',
			'Mercedes Benz',
			'Mercury',
			'MG',
			'MINI',
			'Mitsubishi',
			'Moskovitch',
			'Nissan',
			'NSU',
			'Oldsmobile',
			'Opel',
			'Perodua',
			'Peugeot',
			'Piaggio',
			'Plymouth',
			'Polonez',
			'Polski Fiat',
			'Pontiac',
			'Porsche',
			'Proton',
			'Rayton Fissore',
			'Renault',
			'Rolls Royce',
			'Rover',
			'Saab',
			'Saturn',
			'Shuanghuan',
			'Simca',
			'Smart',
			'SsangYong',
			'Subaru',
			'Suzuki',
			'Talbot',
			'Tata',
			'Tavria',
			'Tesla',
			'Toyota',
			'Trabant',
			'Triumph',
			'TVR',
			'UAZ',
			'Vauxhall',
			'Volkswagen',
			'Volvo',
			'Wartburg',
			'Zastava',
			'ZhiDou',
			'Škoda',
			'Ostalo'
		);

		public $mls_model = [
			'ac'            => [
				'Cobra',
				'Ostalo'
			],
			'acura'         => [
				'CL',
				'MDX',
				'NSX',
				'RDX',
				'Ostalo'
			],
			'AlfaRomeo'     => [
				'4C',
				'33',
				'75',
				'90',
				'145',
				'146',
				'147',
				'155',
				'156',
				'156 Crosswagon',
				'159',
				'164',
				'166',
				'Alfasud',
				'Alfetta',
				'Brera',
				'Giulia',
				'Giulietta',
				'GT',
				'GTV',
				'MiTo',
				'Spider',
				'Sprint',
				'Stelvio',
				'Ostalo'
			],
			'Alpina'        => [
				'B 3',
				'B 5',
				'B 6',
				'B 7',
				'B 8',
				'B 10',
				'B 12',
				'D 3',
				'D 10',
				'Roadster S',
				'Ostalo'
			],
			'Aro'           => [
				'Serija 10',
				'Serija 24',
				'Ostalo'
			],
			'AsiaMotors'    => [
				'Rocsta',
				'Ostalo'
			],
			'AstonMartin'   => [
				'AR 1',
				'DB 9',
				'DB 11',
				'DB S',
				'Lagonda',
				'Rapide',
				'V8 Vantage',
				'Vantage',
				'Ostalo'
			],
			'Audi'          => [
				'80',
				'90',
				'100',
				'200',
				'A1',
				'A2',
				'A3',
				'A4',
				'A4 Allroad',
				'A5',
				'A6',
				'A6 Allroad',
				'A7',
				'A8',
				'Coupe',
				'e-tron',
				'e-tron GT',
				'Q2',
				'Q3',
				'Q5',
				'Q7',
				'Q8',
				'Quattro',
				'R8',
				'RS2',
				'RS3',
				'RS4',
				'RS5',
				'RS6',
				'RS7',
				'RS e-tron GT',
				'RS Q3',
				'RS Q5',
				'RS Q7',
				'S2',
				'S3',
				'S4',
				'S5',
				'S6',
				'S7',
				'S8',
				'SQ5',
				'SQ7',
				'TT',
				'TT RS',
				'TTS',
				'V8',
				'Ostalo',
				'80',
				'90',
				'100',
				'200',
				'A1',
				'A2',
				'A3',
				'A4',
				'A4 Allroad',
				'A5',
				'A6',
				'A6 Allroad',
				'A7',
				'A8',
				'Coupe',
				'e-tron',
				'e-tron GT',
				'Q2',
				'Q3',
				'Q5',
				'Q7',
				'Q8',
				'Quattro',
				'R8',
				'RS2',
				'RS3',
				'RS4',
				'RS5',
				'RS6',
				'RS7',
				'RS e-tron GT',
				'RS Q3',
				'RS Q5',
				'RS Q7',
				'S2',
				'S3',
				'S4',
				'S5',
				'S6',
				'S7',
				'S8',
				'SQ5',
				'SQ7',
				'TT',
				'TT RS',
				'TTS',
				'V8',
				'Ostalo'
			],
			'Austin'        => [
				'Alegro',
				'Metro',
				'Mini',
				'MK',
				'Montego',
				'Moris Marina',
				'Ostalo'
			],
			'Autobianchi'   => [
				'A112',
				'Ostalo'
			],
			'Bentley'       => [
				'Arnage',
				'Bentayga',
				'Continental',
				'Ostalo'
			],
			'BMW'           => [
				'114',
				'116',
				'118',
				'120',
				'123',
				'125',
				'130i',
				'214',
				'218',
				'220',
				'225',
				'228i',
				'315',
				'316',
				'318',
				'320',
				'323',
				'324',
				'325',
				'328',
				'330',
				'335',
				'340i',
				'Compact',
				'318 GT',
				'320 GT',
				'325 GT',
				'328 GT',
				'330 GT',
				'418',
				'420',
				'425',
				'428',
				'430',
				'435',
				'440',
				'518',
				'520',
				'523',
				'524',
				'525',
				'530',
				'535',
				'540',
				'545',
				'550',
				'520 GT',
				'525 GT',
				'528 GT',
				'530 GT',
				'535 GT',
				'540 GT',
				'545 GT',
				'550 GT',
				'630',
				'635',
				'640',
				'645',
				'650',
				'630 GT',
				'640 GT',
				'700',
				'725',
				'728',
				'730',
				'732',
				'735',
				'740',
				'745',
				'750',
				'760',
				'840',
				'850',
				'i3',
				'i8',
				'M 135i',
				'M 140i',
				'M 235i',
				'M 240i',
				'M550',
				'M 550i',
				'M 850i',
				'M1',
				'M2',
				'M3',
				'M4',
				'M5',
				'M6',
				'M8',
				'X3 M',
				'X5 M',
				'X6 M',
				'Z3 M',
				'X1',
				'X2',
				'X3',
				'X4',
				'X5',
				'X6',
				'X7',
				'Z4',
				'Z8',
				'1602',
				'1802',
				'2002',
				'Ostalo'
			],
			'Brilliance'    => [
				'BC3',
				'Ostalo'
			],
			'Bugatti'       => [
				'Veyron',
				'Chiron'
			],
			'Buick'         => [
				'Century',
				'Electra',
				'Park Avenue',
				'Regal',
				'Riviera',
				'Roadmaster',
				'Skyhawk',
				'Ostalo'
			],
			'Cadillac'      => [
				'Allante',
				'Ambassador',
				'BLS',
				'Brougham',
				'CTS',
				'Deville',
				'Eldorado',
				'Escalade',
				'Fleetwood',
				'Seville',
				'SRX',
				'XLR',
				'Ostalo'
			],
			'Chery'         => [
				'Ego',
				'Tengo',
				'Tiggo',
				'Ostalo'
			],
			'Chervolet'     => [
				'Alero',
				'Astro',
				'Avalanche',
				'Aveo',
				'Belair',
				'Beretta',
				'Blazer',
				'Camaro',
				'Cavalier',
				'Chevelle',
				'Corsica',
				'Corvette',
				'Cruze',
				'Epica',
				'Equinox',
				'Evanda',
				'Geo Storm',
				'Impala',
				'Kalos',
				'Lacetti',
				'Lumina',
				'Malibu',
				'Matiz',
				'Niva',
				'Nubira',
				'Orlando',
				'Rezzo',
				'S10',
				'Spark',
				'Tacuma',
				'Tahoe',
				'Trailblazer',
				'Trans Sport',
				'Trax',
				'Venture',
				'Ostalo'
			],
			'Chrysler'      => [
				'200C',
				'300M',
				'300C',
				'Concorde',
				'Crossfire',
				'ES',
				'Grad Voyager',
				'GS',
				'GTS',
				'Interpid',
				'Le Baron',
				'Pacifica',
				'PT Cruiser',
				'Saratoga',
				'Sebring',
				'Stratus',
				'Sunbeam',
				'Town & Country',
				'Valiant',
				'Vision',
				'Voyager',
				'Ostalo'
			],
			'Citroen'       => [
				'2CV',
				'Ami',
				'AX',
				'Berlingo',
				'BX',
				'C-Aircross',
				'C-Crosser',
				'C-ELYSEE',
				'C-Zero',
				'C1',
				'C2',
				'C3',
				'C3 Aircross',
				'C3 Picasso',
				'C3 pluriel',
				'C4',
				'C4 Aircross',
				'C4 Cactus',
				'C4 Grand Picasso',
				'C4 Grand SpaceTourer',
				'C4 Picasso',
				'C4 SpaceTourer',
				'C5',
				'C5 Aircross',
				'C6',
				'C8',
				'C15',
				'CX',
				'DS',
				'DS3',
				'DS4',
				'DS5',
				'DS6',
				'DS7',
				'Dyane',
				'Evasion',
				'GS',
				'GSA',
				'Jumpy',
				'Saxo',
				'SpaceTourer',
				'Velur',
				'Visa',
				'Xantia',
				'XM',
				'Xsara',
				'Xsara Picasso',
				'ZX',
				'Ostalo'
			],
			'Comarth'       => [
				'Cross Rider',
				'Ostalo'
			],
			'Cupra'         => [
				'Ateca',
				'Formentor',
				'Leon',
				'Born',
				'Leon Sportstourer',
				'Ostalo'
			],
			'Dacia'         => [
				'1100',
				'1304',
				'1307',
				'1310',
				'Aro',
				'Dokker',
				'Double',
				'Duster',
				'Lodgy',
				'Logan',
				'Nova',
				'Pickup',
				'Sandero',
				'Solenza',
				'Stepway',
				'Super Nova',
				'Ostalo'
			],
			'Daewoo'        => [
				'Espero',
				'Evanda',
				'Kalos',
				'Korando',
				'Lacetti',
				'Lanos',
				'Leganza',
				'Matiz',
				'Musso',
				'Nexia',
				'Nubira',
				'Racer',
				'Rezzo',
				'Tacuma',
				'Tico',
				'Ostalo'
			],
			'Daihatsu'      => [
				'Applause',
				'Charade',
				'Charmant',
				'Cuore',
				'Feroza',
				'Gran Move',
				'Hijet',
				'Materia',
				'Move',
				'Rocky',
				'Sirion',
				'Taft',
				'Terios',
				'Trevis',
				'Valera',
				'YRV',
				'Ostalo'
			],
			'Dodge'         => [
				'Avenger',
				'Caliber',
				'Challenger',
				'Charger',
				'Caravan',
				'Durango',
				'Grand Caravan',
				'Interpid',
				'Journey',
				'Magnum',
				'Neon',
				'Nitro',
				'RAM',
				'Stealth',
				'Stratus',
				'Ostalo'
			],
			'DR'            => [
				'DR',
				'dr1',
				'Ostalo'
			],
			'Ferrari'       => [
				'195',
				'250',
				'308',
				'328',
				'355',
				'458 Italia',
				'488',
				'599',
				'612',
				'California',
				'Enzo',
				'F12',
				'F 430',
				'Testarossa',
				'Ostalo'
			],
			'Fiat'          => [
				'124',
				'124 Spider',
				'125',
				'126',
				'127',
				'128',
				'130',
				'131',
				'132',
				'133',
				'147',
				'242',
				'500',
				'500C',
				'500L',
				'500X',
				'600',
				'850',
				'900T',
				'1100',
				'1107',
				'1300',
				'Albea',
				'Argenta',
				'Barchetta',
				'Brava',
				'Bravo',
				'Camagnola',
				'Cinquecento',
				'Coupe',
				'Croma',
				'Dino',
				'Doblo',
				'Duna',
				'Elba',
				'EVO',
				'Fiorino',
				'Freemont',
				'Fullback',
				'Grande Punto',
				'Idea',
				'Marea',
				'Marengo',
				'Maxi',
				'Multipla',
				'Palio',
				'Panda',
				'Penny',
				'Punto',
				'Qubo',
				'Regata',
				'Ritmo',
				'Scudo',
				'Sedici',
				'Seicento',
				'Siena',
				'Spider Europa',
				'Stilo',
				'Strada',
				'Tempra',
				'Tipo',
				'Ulysse',
				'Uno',
				'x 1/9',
				'Ostalo'
			],
			'Ford'          => [
				'Aerostar',
				'B-Max',
				'Bronco',
				'C-Max',
				'Capri',
				'Cortina',
				'Cougar',
				'Courier',
				'EcoSport',
				'Edge',
				'Escape',
				'Escort',
				'Excursion',
				'Expedition',
				'Explorer',
				'F 150',
				'F 250',
				'F 350',
				'Festiva',
				'Fiesta',
				'Focus',
				'Fusion',
				'Glaxy',
				'Granada',
				'Grand C-Max',
				'Ka',
				'Ka+',
				'Kuga',
				'Maverick',
				'Mondeo',
				'Mustang',
				'Orion',
				'Puma',
				'Ranger',
				'S-Max',
				'Scorpio',
				'Sierra',
				'Street Ka',
				'Taunus',
				'Taurus',
				'Thunderbird',
				'Tourneo',
				'Tourneo Connect',
				'Tourneo Custom',
				'Windstar',
				'Ostalo'
			],
			'GAZ'           => [
				'3102',
				'Ostalo'
			],
			'GMC'           => [
				'Sierra',
				'Yukon',
				'Ostalo'
			],
			'GreatWall'     => [
				'C20R',
				'C30',
				'H5',
				'H6',
				'Steed',
				'Steed 5',
				'Ostalo'
			],
			'GWM'           => [
				'Hover',
				'Ostalo'
			],
			'Honda'         => [
				'Accord',
				'Aerodeck',
				'Civic',
				'Concerto',
				'CR-V',
				'CR-Z',
				'CRX',
				'e',
				'Element',
				'FR-V',
				'HR-V',
				'Insight',
				'Integra',
				'Jazz',
				'Legend',
				'Logo',
				'Odyssey',
				'Prelude',
				'S2000',
				'Shuttle',
				'Stream',
				'Ostalo'
			],
			'Hummer'        => [
				'H1',
				'H2',
				'H3',
				'Ostalo'
			],
			'Hyundai'       => [
				'Accent',
				'Alcazar',
				'Atos',
				'Aura',
				'Bayon',
				'Coupe',
				'Creta',
				'Elantra',
				'Excel',
				'Galloper',
				'Grandeur',
				'H 1',
				'H 100',
				'i10',
				'i20',
				'i30',
				'i40',
				'Iioniq',
				'ix20',
				'ix35',
				'ix55',
				'Kona',
				'Lantra',
				'Matrix',
				'Nexo',
				'Pony',
				'S-Coupe',
				'Santa Fe',
				'Santamo',
				'Santro',
				'Sonata',
				'Sonica',
				'Terracan',
				'Trajet',
				'Tucson',
				'Veloster',
				'Venue',
				'Verna',
				'XG 30',
				'Ostalo'
			],
			'Infiniti'      => [
				'EX30',
				'EX37',
				'FX30',
				'FX35',
				'FX37',
				'FX45',
				'FX50',
				'G35',
				'G37',
				'M30',
				'M37',
				'Q30',
				'Q50',
				'Q60',
				'Q70',
				'QX30',
				'QX50',
				'QX80',
				'Ostalo'
			],
			'Innocenti'     => [
				'Elba',
				'Ostalo'
			],
			'Isuzu'         => [
				'D-Max',
				'Gemini',
				'Midi',
				'Rodeo',
				'Trooper',
				'Ostalo'
			],
			'Jaguar'        => [
				'E-Pace',
				'E-Type',
				'F pace',
				'I-Pace',
				'F-Type',
				'S-Type',
				'X-Type',
				'XE',
				'XF',
				'XJ',
				'XJ6',
				'XJ8',
				'XJ12',
				'XJ40',
				'XJR',
				'XJS',
				'XK',
				'XKR',
				'Ostalo'
			],
			'Jeep'          => [
				'Cherokee',
				'CJ',
				'Commander',
				'Compass',
				'Grand Cherokee',
				'Liberty',
				'Patriot',
				'Renegade',
				'Wagoneer',
				'Willys',
				'Wrangler',
				'Ostalo'
			],
			'KateyGonow'    => [
				'Troy',
				'Victroy',
				'Ostalo'
			],
			'Kia'           => [
				'Avella Delta',
				'Carens',
				'Carnival',
				'cee\'d',
				'cee\'d sw',
				'Cerato',
				'Clarus',
				'Credos',
				'Joice',
				'Magnetis',
				'Niro',
				'Opirus',
				'Optima',
				'Picanto',
				'Pride',
				'pro_cee\'d',
				'Retona',
				'Rio',
				'Rocsta',
				'Sephia',
				'Shuma',
				'Sorento',
				'Soul',
				'Spectra',
				'Sportage',
				'Stinger',
				'Stonic',
				'Venga',
				'XCeed',
				'Ostalo'
			],
			'KTM'           => [
				'X-BOW R',
				'X-BOW RR',
				'X-BOW GT',
				'Ostalo'
			],
			'Lada'          => [
				'110',
				'111',
				'112',
				'1200',
				'1300',
				'1500',
				'1600',
				'2101',
				'2103',
				'2104',
				'2105',
				'2107',
				'Aleko',
				'Granta',
				'Nadezdhda',
				'Niva',
				'Oka',
				'Priora',
				'Riva',
				'Samara',
				'Vesta',
				'Ostalo',
				'110',
				'111',
				'112',
				'1200',
				'1300',
				'1500',
				'1600',
				'2101',
				'2103',
				'2104',
				'2105',
				'2107',
				'Aleko',
				'Granta',
				'Nadezdhda',
				'Niva',
				'Oka',
				'Priora',
				'Riva',
				'Samara',
				'Vesta',
				'Ostalo'
			],
			'Lamborghini'   => [
				'Aventador',
				'Espada',
				'Gallardo',
				'LM',
				'Urus',
				'Ostalo'
			],
			'Lancia'        => [
				'Aurelia',
				'Beta',
				'Dedra',
				'Delta',
				'Flaminia',
				'Flavia',
				'K',
				'Kappa',
				'Lybra',
				'Musa',
				'Phedra',
				'Prisma',
				'Thema',
				'Thesis',
				'Voyager',
				'Ypsilon',
				'Zeta',
				'Ostalo'
			],
			'LandRover'     => [
				'Defender',
				'Discovery',
				'Discovery Sport',
				'Freelander',
				'Range Rover',
				'Range Rover Autobiography',
				'Range Rover Evoque',
				'Range Rover Velar',
				'Range Rover Vogue',
				'Serija II',
				'Serija III',
				'Ostalo'
			],
			'Lexus'         => [
				'CT 200h',
				'ES',
				'GS 300',
				'GS 450',
				'GX',
				'IS 200',
				'IS 220',
				'IS 300',
				'LC 500',
				'LS 400',
				'LS 430',
				'LS 460',
				'LS 600h',
				'LS 600h L',
				'LX',
				'NX',
				'RC 200',
				'RC 300',
				'RX 200',
				'RX 300',
				'RX 330',
				'RX 350',
				'RX 400',
				'RX 450',
				'SC',
				'UX',
				'Ostalo',
			],
			'Ligier'        => [
				'Ambra',
				'Ostalo'
			],
			'Lincon'        => [
				'Continental',
				'LS',
				'Mark',
				'Navigator',
				'Town car',
				'Ostalo'
			],
			'Linzda'        => [
				'M3',
				'Ostalo'
			],
			'Lotus'         => [
				'Cotina',
				'Elise',
				'Esprit',
				'Super Seven',
				'Ostalo'
			],
			'Mahindra'      => [
				'Bolero',
				'CJ',
				'Goa',
				'Ostalo'
			],
			'Maserati'      => [
				'4200',
				'Ghibli',
				'Granturismo',
				'Levante',
				'Quattroporte',
				'Ostalo'
			],
			'Matra'         => [
				'Bagheera',
				'Ostalo'
			],
			'Maybach'       => [
				'57',
				'62',
				'Ostalo'
			],
			'Mazda'         => [
				'2',
				'3',
				'5',
				'6',
				'121',
				'323',
				'626',
				'929',
				'1500',
				'B 250',
				'BT-50',
				'CX-3',
				'CX-5',
				'CX-7',
				'CX-30',
				'Demio',
				'Millenia',
				'MPV',
				'MX-3',
				'MX-5',
				'MX-6',
				'MX-30',
				'Premacy',
				'Protege',
				'RX-7',
				'RX-8',
				'Serija B',
				'Serija E',
				'Tribute',
				'Xedos',
				'Ostalo'
			],
			'MercedesBenz'  => [
				'180',
				'190',
				'A 140',
				'A 150',
				'A 160',
				'A 170',
				'A 180',
				'A 190',
				'A 210',
				'A 220',
				'A 250',
				'A 45 AMG',
				'B 150',
				'B 160',
				'B 170',
				'B 180',
				'B 200',
				'B 220',
				'B 250',
				'C 160',
				'C 180',
				'C 200',
				'C 220',
				'C 230',
				'C 240',
				'C 250',
				'C 270',
				'C 280',
				'C 300',
				'C 320',
				'C 400',
				'C 32 AMG',
				'C 350',
				'C 36 AMG',
				'C 43 AMG',
				'C 55 AMG',
				'C 63 AMG',
				'CE 200',
				'CE 220',
				'CE 230',
				'CE 300',
				'Citan',
				'CLA 180',
				'CLA 180 Shooting Brake',
				'CLA 200',
				'CLA 200 Shooting Brake',
				'CLA 220',
				'CLA 220 Shooting Brake',
				'CLA 250',
				'CLA 35 AMG',
				'CLA 35 AMG Shooting Brake',
				'CLA 45 AMG',
				'CLA 45 AMG Shooting Brake',
				'CL 220',
				'CL 500',
				'CL 55 AMG',
				'CL 600',
				'CL 60 AMG',
				'CLC 180',
				'CLC 200',
				'CLC 220',
				'CLK 200',
				'CLK 220',
				'CLK 230',
				'CLK 240',
				'CLK 270',
				'CLK 280',
				'CLK 320',
				'CLK 350',
				'CLK 430',
				'CLK 500',
				'CLK 55 AMG',
				'CLK 36 AMG',
				'CLS 220',
				'CLS 220 Shooting Brake',
				'CLS 250',
				'CLS 250 Shooting Brake',
				'CLS 280',
				'CLS 300',
				'CLS 320',
				'CLS 350',
				'CLS 350 Shooting Brake',
				'CLS 400',
				'CLS 400 Shooting Brake',
				'CLS 450',
				'CLS 500',
				'CLS 500 Shooting Brake',
				'CLS 53 AMG',
				'CLS 55 AMG',
				'CLS 63 AMG',
				'CLS 63 AMG Shooting Brake',
				'E 124',
				'E 200',
				'E 220',
				'E 230',
				'E 240',
				'E 250',
				'E 260',
				'E 270',
				'E 280',
				'E 290',
				'E 300',
				'E 320',
				'E 350',
				'E 400',
				'E 420',
				'E 430',
				'E 43 AMG',
				'E 450',
				'E 50',
				'E 500',
				'E 53 AMG',
				'E 55',
				'E 63 AMG',
				'EQC 400',
				'G 230',
				'G 240',
				'G 250',
				'G 270',
				'G 280',
				'G 290',
				'G 300',
				'G 320',
				'G 350',
				'G 400',
				'G 500',
				'G 55 AMG',
				'G 63 AMG',
				'GL 320',
				'GL 350',
				'GL 420',
				'GL 450',
				'GL 500',
				'GL 63 AMG',
				'GLA 45 AMG',
				'GLA 180',
				'GLA 200',
				'GLA 220',
				'GLB 180',
				'GLB 200',
				'GLB 220',
				'GLB 250',
				'GLB 35 AMG',
				'GLC 43 AMG',
				'GLC 63',
				'GLC 200',
				'GLC 250',
				'GLC 300',
				'GLC 350',
				'GLE 43 AMG',
				'GLE 53 AMD',
				'GLE 250',
				'GLE 300',
				'GLE 350',
				'GLE 400',
				'GLE 450',
				'GLE 580',
				'GLK 200',
				'GLK 220',
				'GLK 250',
				'GLK 250',
				'GLK 320',
				'GLK 350',
				'GLS 63 AMG',
				'GLS 350 D',
				'GLS 400',
				'GLS 500',
				'GLS 580',
				'GLS 600',
				'GT',
				'GT 43 AMG',
				'GT 53 AMG',
				'GT 63 AMG',
				'GT-C',
				'GT-R',
				'GT-S',
				'MB 100',
				'ML 230',
				'ML 250',
				'ML 270',
				'ML 280',
				'ML 300',
				'ML 320',
				'ML 350',
				'ML 400',
				'ML 420',
				'ML 430',
				'ML 500',
				'ML 55 AMG',
				'ML 63 AMG',
				'R 280',
				'R 320',
				'R 350',
				'R 500',
				'R 63 AMG',
				'S 220',
				'S 250',
				'S 260',
				'S 280',
				'S 300',
				'S 320',
				'S 350',
				'S 400',
				'S 420',
				'S 430',
				'S 450',
				'S 500',
				'S 55',
				'S 550',
				'S 560 Maybach',
				'S 560 SEL',
				'S 600',
				'S 63 AMG',
				'SL 280',
				'SL 300',
				'SL 320',
				'SL 350',
				'SL 380',
				'SL 450',
				'SL 500',
				'SL 55 AMG',
				'SL 63 AMG',
				'SLC 180',
				'SLC 200',
				'SLC 250',
				'SLC 300',
				'SLC 43 AMG',
				'SLK 200',
				'SLK 230',
				'SLK 250',
				'SLK 320',
				'SLK 32 AMG',
				'SLK 350',
				'SLK 55 AMG',
				'SLS AMG',
				'Vaneo X klasa',
				'Ostalo'
			],
			'Mercury'       => [
				'Capri',
				'Villager',
				'Ostalo'
			],
			'MG'            => [
				'MGA',
				'MGB',
				'MGF',
				'Midget',
				'TF',
				'ZR',
				'ZS',
				'ZS ET',
				'ZT',
				'Ostalo'
			],
			'MINI'          => [
				'1000',
				'1300',
				'Clubman',
				'Cooper',
				'Cooper S',
				'Countryman',
				'John Cooper Works',
				'Paceman',
				'One',
				'Ostalo'
			],
			'Mitsubischi'   => [
				'3000GT',
				'ASX',
				'Carisma',
				'Colt',
				'Cordia',
				'Eclipse',
				'Endeavor',
				'Galant',
				'Grandis',
				'L200',
				'L300',
				'Lancer',
				'Montero',
				'Outlander',
				'Pajero',
				'Pajero Pinin',
				'Pajero Sport',
				'Sapporo',
				'Sigma',
				'Space Gear',
				'Space Runner',
				'Space Star',
				'Space Wagon',
				'Starion',
				'Ostalo'
			],
			'Moskovitch'    => [
				'2137',
				'2140',
				'402',
				'Aleko 2141',
				'Ostalo'
			],
			'Nissan'        => [
				'100 NX',
				'200 SX',
				'280 ZX',
				'300 ZX',
				'350 Z',
				'370 Z',
				'Almera',
				'Almera Tino',
				'Altima',
				'Bluebird',
				'Cherry',
				'Cube',
				'Frontier',
				'GT-R',
				'Juke',
				'Kubistar',
				'Laurel',
				'Leaf',
				'Maxima',
				'Micra',
				'Murano',
				'Navara',
				'Note',
				'Pathfinder',
				'Patrol',
				'Pixo',
				'Praire',
				'Primastar',
				'Primera',
				'Pulsar',
				'Qashqai',
				'Qashqai +2',
				'Rpgie',
				'Semtra',
				'Serena',
				'Silvia',
				'Skyline',
				'Stanza',
				'Sunny',
				'Terrano',
				'Tiida',
				'Titanijum',
				'Vanette',
				'X-Trail',
				'Xterra',
				'Ostalo',
			],
			'NSU'           => [
				'Prinz',
				'Ostalo'
			],
			'Oldsmobile'    => [
				'Alero',
				'Custom Cruiser',
				'Cutlass',
				'Ninety-Eight',
				'Ostalo'
			],
			'Opel'          => [
				'Adam',
				'Admiral',
				'Agila',
				'Ampera',
				'Antara',
				'Arena',
				'Ascona',
				'Astra F',
				'Astra G',
				'Astra H',
				'Astra J',
				'Astra K',
				'Calibra',
				'Cascada',
				'Commodore',
				'Corsa A',
				'Corsa B',
				'Corsa C',
				'Corsa D',
				'Corsa E',
				'Corsa F',
				'Crossland X',
				'Frontera',
				'GT',
				'Grandland X',
				'Insignia',
				'Kadett',
				'Karl',
				'Manta',
				'Meriva',
				'Monterey',
				'Mokka',
				'Mokka X',
				'Monza',
				'Olympia',
				'Omega',
				'Rekord',
				'Senator',
				'Signum',
				'Sintra',
				'Tigra',
				'Vectra A',
				'Vectra B',
				'Vectra C',
				'Zafira',
				'Ostalo'
			],
			'Ostalo'        => [

			],
			'Perodua'       => [
				'Kancil',
				'Ostalo'
			],
			'Peugeot'       => [
				'104',
				'106',
				'107',
				'108',
				'204',
				'205',
				'206',
				'206 plus',
				'207',
				'208',
				'301',
				'304',
				'305',
				'306',
				'307',
				'308',
				'309',
				'403',
				'404',
				'405',
				'406',
				'407',
				'504',
				'505',
				'508',
				'604',
				'605',
				'607',
				'806',
				'807',
				'1007',
				'2008',
				'3008',
				'4007',
				'5008',
				'Bipper',
				'Expert',
				'Partner',
				'Ranch',
				'RCZ',
				'Rifter',
				'TePee',
				'Traveller',
				'Ostalo'
			],
			'Piaggio'       => [
				'Ape',
				'Porter',
				'Ostalo'
			],
			'Plymouth'      => [
				'Breeze',
				'Laser',
				'Voyager',
				'Ostalo'
			],
			'Polonez'       => [
				'Atu',
				'Caro',
				'Coupe',
				'MR',
				'Ostalo'
			],
			'PolskiFiat'    => [
				'125 P',
				'126 P',
				'Ostalo'
			],
			'Pontiac'       => [
				'6000',
				'Bonneville',
				'Chieftain',
				'Fiero',
				'Firebird',
				'G6',
				'Grand Prix',
				'GTO',
				'Le Mans',
				'Solstice',
				'Sunbird',
				'Trans Am',
				'Trans Sport',
				'Ostalo'
			],
			'Porsche'       => [
				'356',
				'718',
				'911',
				'924',
				'928',
				'944',
				'997',
				'Boxster',
				'Carrera GT',
				'Cayenne',
				'Cayman',
				'Macan',
				'Panamera',
				'Taycan',
				'Ostalo'
			],
			'Proton'        => [
				'Seria 400',
				'Ostalo'
			],
			'RaytonFissore' => [
				'Mangum',
				'Ostalo'
			],
			'Renault'       => [
				'Alaskan',
				'Avantime',
				'Captur',
				'Clio',
				'Espace',
				'Exoress',
				'Fluence',
				'Fuego',
				'Grand Escape',
				'Grand Modus',
				'Grand Scenic',
				'Kadjar',
				'Kangoo',
				'Koleos',
				'Laguna',
				'Latitude',
				'Megane',
				'Modus',
				'Nevada',
				'R 4',
				'R 5',
				'R 6',
				'R 8',
				'R 9',
				'R 10',
				'R 11',
				'R 12',
				'R 14',
				'R 18',
				'R 19',
				'R 20',
				'R 21',
				'R 25',
				'R 30',
				'Rapid',
				'RX',
				'Safrane',
				'Scenic',
				'Spider',
				'Super 5',
				'Talisman',
				'Thalia',
				'Twingo',
				'Twizy',
				'Vel Satis',
				'Wind',
				'Zoe',
				'Ostalo'
			],
			'RollsRoyce'    => [
				'Flying Spur',
				'Phantom',
				'Ostalo'
			],
			'Rover'         => [
				'25',
				'45',
				'75',
				'100',
				'200',
				'214',
				'216',
				'220',
				'400',
				'414',
				'416',
				'420',
				'600',
				'618',
				'620',
				'800',
				'820',
				'825',
				'Streetwise',
				'Ostalo'
			],
			'Saab'          => [
				'90',
				'900',
				'9000',
				'9-3',
				'9-5',
				'99',
				'Ostalo'
			],
			'Saturn'        => [
				'SL',
				'Ostalo'
			],
			'Seat'          => [
				'Alhambra',
				'Altea',
				'Altea XL',
				'Arona',
				'Arosa',
				'Ateca',
				'Cordoba',
				'Exeo',
				'Ibiza',
				'Inca',
				'Leon',
				'Malaga',
				'Marbella',
				'Mii',
				'Ronda',
				'Tarraco',
				'Terra',
				'Toledo',
				'Ostalo'
			],
			'Shuanghuan'    => [
				'CEO',
				'Ostalo'
			],
			'Simca'         => [
				'1100',
				'1301',
				'Ostalo'
			],
			'Škoda'         => [
				'100',
				'105',
				'110',
				'120',
				'135',
				'1000 MB',
				'Citigo',
				'Fabia',
				'Favorit',
				'Felicia',
				'Forman',
				'Kamiq',
				'Karoq',
				'Kodiaq',
				'Octavia',
				'Praktik',
				'Rapid',
				'Roomster',
				'Scala',
				'Superb',
				'Yeti',
				'Ostalo'
			],
			'Smart'         => [
				'Crossblade',
				'ForFour',
				'ForTwo',
				'Roadster',
				'Ostalo'
			],
			'SsangYong'     => [
				'Actyon',
				'Family',
				'Korando',
				'Kyron',
				'Musso',
				'Rexton',
				'Rodius',
				'Tivoli',
				'XLV',
				'Ostalo'
			],
			'Subaru'        => [
				'1800',
				'BRZ',
				'Forester',
				'Impreza',
				'Justy',
				'Legacy',
				'Leone',
				'Levorg',
				'Outback',
				'Sumo',
				'SVX',
				'Trezia',
				'Tribeca',
				'Vivio',
				'XT',
				'XV',
				'Ostalo'
			],
			'Suzuki'        => [
				'Alto',
				'Baleno',
				'Cappuccino',
				'Carry',
				'Calerio',
				'Grand Vitara',
				'Ignis',
				'Jimny',
				'Kizashi',
				'Liana',
				'Maruti',
				'Ritz',
				'SJ Samurai',
				'Splash',
				'Super Carry',
				'Swift',
				'SX4',
				'SX4 S-Cross',
				'Vitara',
				'Wagon R+',
				'Ostalo'
			],
			'Talbot'        => [
				'Horizen',
				'Murena',
				'Samba',
				'Solara',
				'Ostalo'
			],
			'Tata'          => [
				'Indica',
				'Indigo',
				'Pick-Up',
				'Safari',
				'Sumo',
				'Telcoline',
				'TelcoSport',
				'Ostalo'
			],
			'Tavria'        => [
				'1102',
				'Ostalo'
			],
			'Tesla'         => [
				'Model S',
				'Model 3',
				'Model X',
				'Model Y',
				'Ostalo'
			],
			'Toyota'        => [
				'4Runner',
				'Auris',
				'Avensis',
				'Avensis Verso',
				'Aygo',
				'C-HR',
				'Camry',
				'Carina',
				'Celica',
				'Corolla',
				'Corolla Verso',
				'Corona',
				'Cressida',
				'GT86',
				'Hiace',
				'Highlander',
				'Hilux',
				'iQ',
				'Land Cruiser',
				'LC',
				'Liteace',
				'Matrix',
				'MR2',
				'Paseo',
				'Pickup',
				'Picnic',
				'Previa',
				'Prius',
				'Prius +',
				'Prius Plug In',
				'Proace City',
				'Proace City Verso',
				'RAV 4',
				'Sienna',
				'Starlet',
				'Supra',
				'Tercel',
				'Tundra',
				'Urban Cruiser',
				'Verso',
				'Verso-S',
				'Yaris',
				'Yaris Verso',
				'Ostalo'
			],
			'Trabant'       => [
				'601',
				'Ostalo'
			],
			'Triumph'       => [
				'Herald',
				'Spitfire',
				'Ostalo'
			],
			'TVR'           => [
				'Cerbera',
				'Chimaera',
				'Griffith',
				'S2',
				'S4C',
				'Sagaris',
				'Tuscan',
				'V8S',
				'Ostalo'
			],
			'UAZ'           => [
				'69',
				'452',
				'469',
				'31514',
				'Ostalo'
			],
			'Vauxhall'      => [
				'Astra',
				'Vectra',
				'Victor',
				'Ostalo'
			],
			'Volksvagen'    => [
				'181',
				'183',
				'Amarok',
				'Arteon',
				'Bora',
				'Buggy',
				'Buba',
				'Nova Buba',
				'Caddy',
				'Corrado',
				'Cross Polo',
				'Derby',
				'EOS',
				'Fox',
				'Golf 1',
				'Golf 2',
				'Golf 3',
				'Golf 4',
				'Golf 5',
				'Golf 6',
				'Golf 7',
				'Golf 8',
				'Golf Plus',
				'Golf Sportsvan',
				'ID.3',
				'ID.4',
				'Jetta',
				'Lupo',
				'Passat B1',
				'Passat B2',
				'Passat B3',
				'Passat B4',
				'Passat B5',
				'Passat B5.5',
				'Passat B6',
				'Passat B7',
				'Passat B7 Alltrack',
				'Passat B8',
				'Passat B8 Alltrack',
				'Passat CC',
				'Phaeton',
				'Polo',
				'Santana',
				'Scirocco',
				'Sharan',
				'T-Cross',
				'T-Roc',
				'Taro',
				'Tiguan',
				'Touareg',
				'Touran',
				'up!',
				'Vento',
				'Ostalo'
			],
			'Volvo'         => [
				'П210',
				'66',
				'142',
				'144',
				'240',
				'244',
				'245',
				'340',
				'440',
				'460',
				'480',
				'740',
				'744',
				'745',
				'760',
				'780',
				'850',
				'940',
				'945',
				'960',
				'Amazon',
				'C30',
				'C70',
				'Polar',
				'S40',
				'S60',
				'S70',
				'S80',
				'S90',
				'V40',
				'V50',
				'V60',
				'V70',
				'V90',
				'XC40',
				'XC60',
				'XC90',
				'Ostalo'
			],
			'Wartburg'      => [
				'311',
				'353',
				'Ostalo'
			],
			'Zastava'       => [
				'10',
				'101',
				'128',
				'1300',
				'1500',
				'750',
				'850',
				'AR 55',
				'Florida',
				'Florida In',
				'Koral',
				'Koral In',
				'Poly',
				'Skala 55',
				'Yugo 45',
				'Yugo 55',
				'Yugo 60',
				'Yugo 65',
				'Yugo Cabrio',
				'Yugo Ciao',
				'Yugo In L',
				'Yugo Tempo',
				'Ostalo'
			],
			'ZhiDou'        => [
				'Ostalo'
			]
		];

		public function __construct() {
			include MLAB_STUDIO_DIR . 'src/config/my-account/my-account-pages/Mls_My_Account_Pages.php';
			include MLAB_STUDIO_DIR . 'src/config/my-account/my-account-pages/Mls_My_Account_Process_Declaration.php';
			include MLAB_STUDIO_DIR . 'src/config/favorites-ads/Mls_Favorites_Ads.php';

			// CRON DAILY
			add_action( 'wp', array( $this, 'mls_daily_cron_post_delete' ) );
			add_action( 'mls_delete_expired_posts', array( $this, 'mls_delete_expired_posts_callback' ) );

			// Delete post on timestamp
			// $this->mls_delete_post_timestamp();
		}


		/**
		 * Sending the value to wp_usermeta
		 *
		 * @param $meta_key string Desired user_meta_key
		 * @param $meta_value string Desired user_meta_value
		 */
		public function mls_send_meta( $meta_key, $meta_value ) {
			if ( is_user_logged_in() ) {
				$user_id   = wp_get_current_user();
				$new_value = $meta_value;

				update_user_meta( $user_id->ID, $meta_key, $new_value );

				if ( get_user_meta( $user_id->ID, $meta_key, true ) != $new_value ) {
					wp_die( 'An error occurred' );
				}
			}
		}

		/**
		 * Getting the user meta value
		 *
		 * @param $meta_key string Passing meta key
		 *
		 * @return string
		 */
		public function mls_get_meta( $meta_key ) {
			if ( is_user_logged_in() ) {
				$user_id             = wp_get_current_user();
				$all_meta_user_value = get_user_meta( $user_id->ID );

				return ! empty( $all_meta_user_value[ $meta_key ][0] ) ? $all_meta_user_value[ $meta_key ][0] : '';
			}
		}

		/**
		 * If is company
		 *
		 * @return bool
		 */
		public function mls_is_company() {
			if ( $this->mls_get_meta( 'mls_company_person' ) ) {
				return true;
			}
		}

		/**
		 * If is person
		 *
		 * @return bool
		 */
		public function mls_is_person() {
			if ( $this->mls_get_meta( 'mls_person' ) ) {
				return true;
			}
		}

		/**
		 * Get meta key for editing single ads
		 *
		 * @param $post_id
		 * @param $meta_key
		 *
		 * @return string
		 */
		public function mls_get_edit_meta( $post_id, $meta_key ) {
			if ( ! empty( $meta_key ) ) {
				echo get_post_meta( $post_id, $meta_key, true );
			}
		}

		public function mls_daily_cron_post_delete() {
			if ( ! wp_next_scheduled( 'mls_delete_expired_posts' ) ) {
				wp_schedule_event( time(), 'hourly', 'mls_delete_expired_posts' ); // change back to 'daily'
			}
		}

		public function mls_delete_expired_posts_callback() {
			wp_delete_post( 663 ); // deleted immediately - check: https://wordpress.stackexchange.com/questions/152786/posts-to-expire-deleted-after-a-date
		}

		/**
		 * Timestamp in days
		 *
		 * @param int $day Number of timestamp days
		 *
		 * @return false|string
		 */
//		public function mls_promotion_day_counting( $day ) {
//			$number_of_days = ( $day == 1 ) ? ' day' : ' days';
//
//			return date( 'd.m.Y', strtotime( '+ ' . $day . $number_of_days ) );
//		}

//		public function mls_delete_post_timestamp() {
//			$arr = array(
//				'post_type'      => 'naslovna_oglasi',
//				'orderby'        => 'post_id',
//				'posts_per_page' => - 1,
//			);
//
//			$query = new WP_Query( $arr );
//
//			if ( $query->have_posts() ) {
//				while ( $query->have_posts() ) {
//					$query->the_post();
//
//					$expiration_date      = get_post_meta( get_the_ID(), '_mls_naslovna_timestamp', true );
//					$expiration_date_time = strtotime( $expiration_date );
//
//					if ( $expiration_date_time < time() ) {
//						wp_delete_post( get_the_ID() );
//					}
//				}
//				wp_reset_postdata();
//			}
//		}
	}

	new Mls_Config();
}
